#!/bin/bash
# monnect – interactive setup. Run this once on EACH Mac, from a real terminal
# (Terminal.app / iTerm / Ghostty), because blueutil needs Bluetooth permission
# granted to the terminal app.
set -uo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DIR/lib.sh"

find_blueutil

echo "== monnect setup =="
echo

# --- Bluetooth permission check -------------------------------------------
if ! "$BLUEUTIL" --paired >/dev/null 2>&1; then
  cat <<'EOF'
Your terminal app does not have Bluetooth access yet.

  1. Open System Settings > Privacy & Security > Bluetooth
  2. Enable (or add with +) the terminal app you are running this from
  3. Restart the terminal app and run ./setup.sh again
EOF
  exit 1
fi

# --- Pick devices ----------------------------------------------------------
echo "Paired Bluetooth devices on this Mac:"
echo
paired="$("$BLUEUTIL" --paired)"
i=0
addrs=()
while IFS= read -r line; do
  addr="$(echo "$line" | sed -n 's/^address: \([0-9a-f-]*\).*/\1/p')"
  name="$(echo "$line" | sed -n 's/.*name: "\([^"]*\)".*/\1/p')"
  [ -n "$addr" ] || continue
  i=$((i+1))
  addrs+=("$addr")
  printf "  %2d) %-30s %s\n" "$i" "${name:-<unnamed>}" "$addr"
done <<< "$paired"

if [ $i -eq 0 ]; then
  echo "No paired devices found. Pair your Magic Mouse/Keyboard with this Mac first"
  echo "(plug in the cable once), then re-run ./setup.sh."
  exit 1
fi

echo
read -r -p "Numbers of the devices to switch (e.g. '1 3'): " selection
devices=()
for n in $selection; do
  idx=$((n-1))
  [ $idx -ge 0 ] && [ $idx -lt $i ] || { echo "invalid number: $n"; exit 1; }
  devices+=("${addrs[$idx]}")
done
[ ${#devices[@]} -gt 0 ] || { echo "nothing selected"; exit 1; }

# --- Peer Mac --------------------------------------------------------------
echo
echo "SSH target for the OTHER Mac (e.g. 'user@Works-MacBook-Pro.local'"
echo "or an alias from ~/.ssh/config). Leave empty to configure later:"
read -r -p "peer ssh host: " peer_host

peer_dir="$DIR"
if [ -n "$peer_host" ]; then
  read -r -p "monnect directory on the other Mac [default: $DIR]: " answer
  [ -n "$answer" ] && peer_dir="$answer"
fi

# --- Write config ----------------------------------------------------------
{
  echo "# monnect config – generated by setup.sh on $(date '+%Y-%m-%d')"
  echo "DEVICES=("
  for d in "${devices[@]}"; do echo "  \"$d\""; done
  echo ")"
  echo "PEER_HOST=\"$peer_host\""
  echo "PEER_MONNECT_DIR=\"$peer_dir\""
} > "$DIR/config.sh"

echo
echo "Wrote $DIR/config.sh"

# --- Test peer connectivity ------------------------------------------------
if [ -n "$peer_host" ]; then
  echo "Testing ssh to $peer_host..."
  if ssh -o BatchMode=yes -o ConnectTimeout=5 "$peer_host" true 2>/dev/null; then
    echo "ssh OK"
  else
    cat <<EOF
Could not ssh to $peer_host without a password. To fix:
  - On the other Mac: System Settings > General > Sharing > enable Remote Login
  - On this Mac:   ssh-keygen -t ed25519   (if you have no key yet)
                   ssh-copy-id $peer_host
EOF
  fi
fi

echo
echo "Done. Grab the peripherals on this Mac with:  ./switch.sh"
